In [1]:
sentences = [
    "i like deep learning",
    "i like machine learning",
    "i love deep learning",
    "i love machine learning"
]

sentences


['i like deep learning',
 'i like machine learning',
 'i love deep learning',
 'i love machine learning']

In [2]:
sentences = [
    "i like deep learning",
    "i like machine learning",
    "i like neural networks",
    "i like data science",
    "i like artificial intelligence",

    "i love deep learning",
    "i love machine learning",
    "i love neural networks",
    "i love data science",
    "i love artificial intelligence",

    "we like deep learning",
    "we like machine learning",
    "we like neural networks",
    "we like data science",
    "we like artificial intelligence",

    "we love deep learning",
    "we love machine learning",
    "we love neural networks",
    "we love data science",
    "we love artificial intelligence",

    "they like deep learning",
    "they like machine learning",
    "they like neural networks",
    "they like data science",
    "they like artificial intelligence",

    "they love deep learning",
    "they love machine learning",
    "they love neural networks",
    "they love data science",
    "they love artificial intelligence",

    "students like deep learning",
    "students like machine learning",
    "students like neural networks",
    "students like data science",
    "students like artificial intelligence",

    "researchers love deep learning",
    "researchers love machine learning",
    "researchers love neural networks",
    "researchers love data science",
    "researchers love artificial intelligence"
]


In [3]:
tokenized = [s.split() for s in sentences]
tokenized


[['i', 'like', 'deep', 'learning'],
 ['i', 'like', 'machine', 'learning'],
 ['i', 'like', 'neural', 'networks'],
 ['i', 'like', 'data', 'science'],
 ['i', 'like', 'artificial', 'intelligence'],
 ['i', 'love', 'deep', 'learning'],
 ['i', 'love', 'machine', 'learning'],
 ['i', 'love', 'neural', 'networks'],
 ['i', 'love', 'data', 'science'],
 ['i', 'love', 'artificial', 'intelligence'],
 ['we', 'like', 'deep', 'learning'],
 ['we', 'like', 'machine', 'learning'],
 ['we', 'like', 'neural', 'networks'],
 ['we', 'like', 'data', 'science'],
 ['we', 'like', 'artificial', 'intelligence'],
 ['we', 'love', 'deep', 'learning'],
 ['we', 'love', 'machine', 'learning'],
 ['we', 'love', 'neural', 'networks'],
 ['we', 'love', 'data', 'science'],
 ['we', 'love', 'artificial', 'intelligence'],
 ['they', 'like', 'deep', 'learning'],
 ['they', 'like', 'machine', 'learning'],
 ['they', 'like', 'neural', 'networks'],
 ['they', 'like', 'data', 'science'],
 ['they', 'like', 'artificial', 'intelligence'],
 ['th

In [4]:
vocab = sorted(set(word for sent in tokenized for word in sent))
vocab, len(vocab)


(['artificial',
  'data',
  'deep',
  'i',
  'intelligence',
  'learning',
  'like',
  'love',
  'machine',
  'networks',
  'neural',
  'researchers',
  'science',
  'students',
  'they',
  'we'],
 16)

In [5]:
word_to_ix = {w: i for i, w in enumerate(vocab)}
ix_to_word = {i: w for w, i in word_to_ix.items()}

word_to_ix


{'artificial': 0,
 'data': 1,
 'deep': 2,
 'i': 3,
 'intelligence': 4,
 'learning': 5,
 'like': 6,
 'love': 7,
 'machine': 8,
 'networks': 9,
 'neural': 10,
 'researchers': 11,
 'science': 12,
 'students': 13,
 'they': 14,
 'we': 15}

In [6]:
encoded = [[word_to_ix[w] for w in sent] for sent in tokenized]
encoded


[[3, 6, 2, 5],
 [3, 6, 8, 5],
 [3, 6, 10, 9],
 [3, 6, 1, 12],
 [3, 6, 0, 4],
 [3, 7, 2, 5],
 [3, 7, 8, 5],
 [3, 7, 10, 9],
 [3, 7, 1, 12],
 [3, 7, 0, 4],
 [15, 6, 2, 5],
 [15, 6, 8, 5],
 [15, 6, 10, 9],
 [15, 6, 1, 12],
 [15, 6, 0, 4],
 [15, 7, 2, 5],
 [15, 7, 8, 5],
 [15, 7, 10, 9],
 [15, 7, 1, 12],
 [15, 7, 0, 4],
 [14, 6, 2, 5],
 [14, 6, 8, 5],
 [14, 6, 10, 9],
 [14, 6, 1, 12],
 [14, 6, 0, 4],
 [14, 7, 2, 5],
 [14, 7, 8, 5],
 [14, 7, 10, 9],
 [14, 7, 1, 12],
 [14, 7, 0, 4],
 [13, 6, 2, 5],
 [13, 6, 8, 5],
 [13, 6, 10, 9],
 [13, 6, 1, 12],
 [13, 6, 0, 4],
 [11, 7, 2, 5],
 [11, 7, 8, 5],
 [11, 7, 10, 9],
 [11, 7, 1, 12],
 [11, 7, 0, 4]]

In [7]:
import numpy as np

V = len(vocab)

def one_hot(idx, V):
    v = np.zeros(V)
    v[idx] = 1
    return v

one_hot(encoded[0][0], V)


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
import numpy as np

V = len(vocab)

def one_hot(idx, V):
    v = torch.zeros(V)
    v[idx] = 1.0
    return v


X_train = []
Y_train = []

for sent in encoded:
    X_sent = []
    Y_sent = []
    
    for t in range(len(sent) - 1):
        X_sent.append(one_hot(sent[t], V))   # torch tensor (V,)
        Y_sent.append(sent[t + 1])           # python int
    
    X_train.append(torch.stack(X_sent))              # (T, V)
    Y_train.append(torch.tensor(Y_sent, dtype=torch.long))  # (T,)



In [25]:
X_train

[tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0.,

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [26]:
class SimpleRNN(nn.Module):
    def __init__(self, vocab_size, hidden_size):
        super().__init__()
        
        self.V = vocab_size
        self.H = hidden_size
        
        self.Wxh = nn.Linear(vocab_size, hidden_size, bias=True)
        self.Whh = nn.Linear(hidden_size, hidden_size, bias=False)
        self.Why = nn.Linear(hidden_size, vocab_size, bias=True)
        
    def forward(self, X):
        """
        X: (T, V) one-hot tensor
        """
        T = X.shape[0]
        h = torch.zeros(self.H)   # h0
        
        outputs = []
        
        for t in range(T):
            x_t = X[t]
            h = torch.tanh(self.Wxh(x_t) + self.Whh(h))
            y_t = self.Why(h)
            outputs.append(y_t)
        
        return torch.stack(outputs)  # (T, V)


In [27]:
V = len(vocab)
H = 16

model = SimpleRNN(V, H)

X0 = torch.tensor(X_train[0], dtype=torch.float32)
Y0 = torch.tensor(Y_train[0], dtype=torch.long)

logits = model(X0)

logits.shape


C:\Users\DELL\AppData\Local\Temp\ipykernel_14808\1265691402.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X0 = torch.tensor(X_train[0], dtype=torch.float32)
C:\Users\DELL\AppData\Local\Temp\ipykernel_14808\1265691402.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Y0 = torch.tensor(Y_train[0], dtype=torch.long)


torch.Size([3, 16])

In [37]:
class SimpleRNN(nn.Module):
    def __init__(self, vocab_size, hidden_size):
        super().__init__()
        
        self.V = vocab_size
        self.H = hidden_size
        
        self.Wxh = nn.Linear(vocab_size, hidden_size)
        self.Whh = nn.Linear(hidden_size, hidden_size, bias=False)
        self.Why = nn.Linear(hidden_size, vocab_size)
        
    def forward(self, X):
        """
        X: (T, V)
        returns logits: (T, V)
        """
        T = X.shape[0]
        h = torch.zeros(self.H)
        
        outputs = []
        
        for t in range(T):
            x_t = X[t]                       # (V,)
            h = torch.tanh(
                self.Wxh(x_t) + self.Whh(h)  # (H,)
            )
            y_t = self.Why(h)                # (V,)
            outputs.append(y_t)
        
        return torch.stack(outputs)          # (T, V)



In [44]:
H = 8  # hidden size

model = SimpleRNN(V, H)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)


In [45]:
X0 = X_train[0]
Y0 = Y_train[0]

logits = model(X0)
loss = F.cross_entropy(logits, Y0)

logits.shape, loss.item()


(torch.Size([3, 16]), 2.574345588684082)

In [46]:
model.Why.out_features


16

In [47]:
model.H


8

In [48]:
epochs = 300

for epoch in range(epochs+1):
    total_loss = 0.0
    
    for X, Y in zip(X_train, Y_train):
        optimizer.zero_grad()
        
        logits = model(X)              # forward
        loss = F.cross_entropy(logits, Y)
        
        loss.backward()                # BPTT
        optimizer.step()
        
        total_loss += loss.item()
    
    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {total_loss:.4f}")


Epoch 0, Loss: 96.9898
Epoch 50, Loss: 29.1653
Epoch 100, Loss: 28.9579
Epoch 150, Loss: 28.8823
Epoch 200, Loss: 28.8587
Epoch 250, Loss: 28.8386
Epoch 300, Loss: 28.8075


In [49]:
def predict(model, start_words, steps=5):
    model.eval()
    
    words = start_words.split()
    
    for _ in range(steps):
        X = torch.stack([
            one_hot(word_to_ix[w], V) for w in words
        ])
        
        logits = model(X)
        probs = F.softmax(logits[-1], dim=0)
        next_idx = torch.argmax(probs).item()
        words.append(ix_to_word[next_idx])
    
    return " ".join(words)


In [50]:
predict(model, "i like")

'i like neural networks like deep learning'

In [51]:
predict(model, "they love")

'they love neural networks like deep learning'

In [52]:
predict(model, "students like")

'students like data science love neural networks'

In [53]:
predict(model,"i love")

'i love neural networks like deep learning'

In [57]:
predict(model,"like")

'like like deep learning love neural'

In [58]:
predict(model,"researchers love")

'researchers love data science love neural networks'